name: walka
description: WALKA premium mobile storefront prototype.
publish_to: none
version: 1.2.0+121

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  http: ^1.6.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/branding/walka_logo.svg
